name: GastroPro - Local
values:
  - key: base_url_carrito
    value: 'http://localhost:3001'
    type: default
    enabled: true
  - key: base_url_reservas
    value: 'http://localhost:3002'
    type: default
    enabled: true
  - key: base_url_menu
    value: 'http://localhost:3003'
    type: default
    enabled: true
  - key: base_url_contacto
    value: 'http://localhost:3000'
    type: default
    enabled: true
